[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./out" },
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./" }
]
ffi = true
build_info = true
extra_output = ["storageLayout"]